import { makeStyles } from '@material-ui/core/styles';
import { deepPurple } from '@material-ui/core/colors';

export default makeStyles((theme) => ({
  appBar: {
    borderRadius: 12,
    margin: theme.spacing(1.25, 0),
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: theme.spacing(1, 2.5),
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
    transition: 'none',
    '&:hover': {
      boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
    },
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'column',
      padding: theme.spacing(1.5, 2),
    },
  },
  heading: {
    color: theme.palette.primary.main,
    textDecoration: 'none',
    fontSize: '2em',
    fontWeight: 300,
  },
  image: {
    marginLeft: '10px',
    marginTop: '5px',
  },
  toolbar: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    paddingRight: 0,
    [theme.breakpoints.down('sm')]: {
      width: '100%',
      justifyContent: 'center',
    },
  },
  profile: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    flexWrap: 'nowrap',
    minWidth: 0,
    maxWidth: '100%',
    [theme.breakpoints.down('sm')]: {
      marginTop: theme.spacing(1),
      flexWrap: 'wrap',
      justifyContent: 'center',
    },
  },
  logout: {
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    padding: '8px 16px',
    minHeight: 36,
    borderRadius: 10,
    lineHeight: 1.2,
    color: '#5c5c5c',
    border: '1px solid #e0e0e0',
    backgroundColor: '#fff',
    boxShadow: 'none',
    flexShrink: 0,
    transition: 'background-color 0.2s ease, border-color 0.2s ease, color 0.2s ease',
    '& .MuiButton-startIcon': {
      marginRight: 6,
    },
    '&:hover': {
      backgroundColor: '#e8eaf6',
      border: '1px solid #7986cb',
      color: '#283593',
      boxShadow: 'none',
    },
    '&.MuiButton-outlined': {
      border: '1px solid #e0e0e0',
      padding: '8px 16px',
      '&:hover': {
        border: '1px solid #7986cb',
        backgroundColor: '#e8eaf6',
      },
    },
  },
  logoutIcon: {
    fontSize: 18,
  },
  userName: {
    display: 'block',
    fontWeight: 600,
    fontSize: '0.9375rem',
    lineHeight: 1.2,
    maxWidth: 160,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  brandContainer: {
    display: 'flex',
    alignItems: 'center',
    textDecoration: 'none',
    color: 'inherit',
    '&:hover': {
      textDecoration: 'none',
      opacity: 1,
    },
  },
  purple: {
    color: theme.palette.getContrastText(deepPurple[500]),
    backgroundColor: deepPurple[500],
  },
  signInButton: {
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.875rem',
    letterSpacing: '0.02em',
    padding: '10px 22px',
    minHeight: 40,
    borderRadius: 10,
    lineHeight: 1.2,
    boxShadow: 'none',
    backgroundColor: '#3f51b5',
    color: '#fff',
    transition: 'background-color 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      backgroundColor: '#283593',
      color: '#fff',
      boxShadow: '0 2px 6px rgba(40, 53, 147, 0.4)',
    },
    '&.MuiButton-containedPrimary': {
      boxShadow: 'none',
      backgroundColor: '#3f51b5',
      '&:hover': {
        backgroundColor: '#283593',
        boxShadow: '0 2px 6px rgba(40, 53, 147, 0.4)',
      },
    },
  },
}));