import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  root: {
    width: '100%',
    '& .MuiTextField-root': {
      marginTop: theme.spacing(0.75),
      marginBottom: theme.spacing(0.75),
      marginLeft: 0,
      marginRight: 0,
      width: '100%',
      '& .MuiOutlinedInput-root': {
        borderRadius: 10,
        backgroundColor: '#fff',
      },
      '& .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline': {
        borderColor: '#3f51b5',
      },
      '& .MuiInputLabel-root': {
        color: '#555',
        fontWeight: 500,
      },
    },
  },
  paper: {
    padding: theme.spacing(2.5),
    marginTop: theme.spacing(2.5),
    borderRadius: 15,
    backgroundColor: '#fafafa',
    boxShadow: '0 6px 20px rgba(0,0,0,0.06)',
    transition: 'all 0.3s ease',
    display: 'flex',
    justifyContent: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  fileInput: {
    position: 'relative',
    width: '100%',
    boxSizing: 'border-box',
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(0.5),
    borderRadius: 10,
    padding: theme.spacing(1, 1.25),
    backgroundColor: '#fff',
    border: '1px solid rgba(0, 0, 0, 0.12)',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(1.25),
    minHeight: 44,
    flexWrap: 'nowrap',
  },
  fileInputHidden: {
    position: 'absolute',
    width: 0,
    height: 0,
    opacity: 0,
    overflow: 'hidden',
    pointerEvents: 'none',
  },
  chooseFileButton: {
    flexShrink: 0,
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    minHeight: 34,
    padding: theme.spacing(0.5, 1.5),
    borderRadius: 8,
    borderWidth: 1.5,
    boxShadow: 'none',
    '&:hover': {
      boxShadow: 'none',
    },
  },
  fileHint: {
    flex: 1,
    minWidth: 0,
    fontSize: '0.8125rem',
    color: theme.palette.text.secondary,
    lineHeight: 1.3,
  },
  actionsRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing(1.25),
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: theme.spacing(1.5),
  },
  buttonSubmit: {
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    letterSpacing: '0.01em',
    minHeight: 34,
    padding: theme.spacing(0.5, 2.25),
    borderRadius: 8,
    flex: '1 1 auto',
    minWidth: 112,
    maxWidth: 168,
    border: 'none',
    background: 'linear-gradient(180deg, #5c6bc0 0%, #3f51b5 100%)',
    color: '#fff',
    boxShadow: '0 1px 3px rgba(63, 81, 181, 0.35)',
    transition: 'filter 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      filter: 'brightness(1.06)',
      boxShadow: '0 2px 8px rgba(63, 81, 181, 0.45)',
      background: 'linear-gradient(180deg, #5c6bc0 0%, #3f51b5 100%)',
    },
  },
  clearButton: {
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    letterSpacing: '0.01em',
    minHeight: 34,
    padding: theme.spacing(0.5, 2.25),
    borderRadius: 8,
    flex: '1 1 auto',
    minWidth: 112,
    maxWidth: 168,
    borderWidth: 1.5,
    borderStyle: 'solid',
    borderColor: theme.palette.grey[400],
    backgroundColor: '#fff',
    color: theme.palette.text.primary,
    boxShadow: 'none',
    transition: 'border-color 0.2s ease, background-color 0.2s ease',
    '&:hover': {
      borderColor: theme.palette.grey[600],
      backgroundColor: theme.palette.grey[100],
      boxShadow: 'none',
    },
  },
  titleTypography: {
    fontWeight: 600,
    fontSize: '1.125rem',
    marginBottom: theme.spacing(1),
    color: '#222',
    width: '100%',
    textAlign: 'center',
  },
}));