import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  root: {
    width: '100%',
    '& .MuiTextField-root': {
      marginTop: theme.spacing(0.75),
      marginBottom: theme.spacing(0.75),
      marginLeft: 0,
      marginRight: 0,
      width: '100%',
      '& .MuiOutlinedInput-root': {
        borderRadius: 10,
        backgroundColor: '#fff',
      },
      '& .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline': {
        borderColor: '#3f51b5',
      },
      '& .MuiInputLabel-root': {
        color: '#555',
        fontWeight: 500,
      },
    },
  },
  paper: {
    padding: theme.spacing(2.5),
    marginTop: theme.spacing(2.5),
    borderRadius: 15,
    backgroundColor: '#fafafa',
    boxShadow: '0 6px 20px rgba(0,0,0,0.06)',
    transition: 'all 0.3s ease',
    display: 'flex',
    justifyContent: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: 400,
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  fileInput: {
    position: 'relative',
    width: '100%',
    boxSizing: 'border-box',
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(0.5),
    borderRadius: 10,
    padding: theme.spacing(1, 1.25),
    backgroundColor: '#fff',
    border: '1px solid rgba(0, 0, 0, 0.12)',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing(1.25),
    minHeight: 44,
    flexWrap: 'nowrap',
  },
  fileInputHidden: {
    position: 'absolute',
    width: 0,
    height: 0,
    opacity: 0,
    overflow: 'hidden',
    pointerEvents: 'none',
  },
  chooseFileButton: {
    flexShrink: 0,
    boxSizing: 'border-box',
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    minHeight: 36,
    padding: '8px 16px',
    borderRadius: 10,
    lineHeight: 1.2,
    border: '1px solid #d5d5d5',
    color: '#424242',
    backgroundColor: '#eceff1',
    boxShadow: 'none',
    transition: 'background-color 0.2s ease, border-color 0.2s ease, color 0.2s ease',
    '&:hover': {
      backgroundColor: '#cfd8dc',
      borderColor: '#90a4ae',
      color: '#263238',
      boxShadow: 'none',
    },
    '&.MuiButton-outlined': {
      padding: '8px 16px',
      border: '1px solid #d5d5d5',
      backgroundColor: '#eceff1',
      '&:hover': {
        border: '1px solid #90a4ae',
        backgroundColor: '#cfd8dc',
      },
    },
  },
  fileHint: {
    flex: 1,
    minWidth: 0,
    fontSize: '0.8125rem',
    color: theme.palette.text.secondary,
    lineHeight: 1.3,
  },
  actionsRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing(1.25),
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: theme.spacing(1.5),
  },
  buttonSubmit: {
    boxSizing: 'border-box',
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    letterSpacing: '0.01em',
    minHeight: 34,
    padding: theme.spacing(0.5, 2.25),
    borderRadius: 8,
    flex: '1 1 auto',
    minWidth: 112,
    maxWidth: 168,
    border: 'none',
    background: 'linear-gradient(180deg, #5c6bc0 0%, #3f51b5 100%)',
    color: '#fff',
    boxShadow: '0 2px 6px rgba(63, 81, 181, 0.28)',
    transition: 'background 0.2s ease, box-shadow 0.2s ease',
    '&:hover': {
      background: 'linear-gradient(180deg, #4a5aa8 0%, #2e3d8f 100%)',
      boxShadow: '0 2px 6px rgba(41, 53, 130, 0.45)',
    },
    '&.MuiButton-contained': {
      boxShadow: '0 2px 6px rgba(63, 81, 181, 0.28)',
    },
    '&.MuiButton-contained:hover': {
      boxShadow: '0 2px 6px rgba(41, 53, 130, 0.45)',
    },
    '&.MuiButton-containedPrimary': {
      background: 'linear-gradient(180deg, #5c6bc0 0%, #3f51b5 100%)',
      color: '#fff',
      boxShadow: '0 2px 6px rgba(63, 81, 181, 0.28)',
      '&:hover': {
        background: 'linear-gradient(180deg, #4a5aa8 0%, #2e3d8f 100%)',
        boxShadow: '0 2px 6px rgba(41, 53, 130, 0.45)',
      },
    },
  },
  clearButton: {
    boxSizing: 'border-box',
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    letterSpacing: '0.01em',
    minHeight: 34,
    padding: theme.spacing(0.5, 2.25),
    borderRadius: 8,
    flex: '1 1 auto',
    minWidth: 112,
    maxWidth: 168,
    border: '2px solid',
    borderColor: theme.palette.grey[400],
    backgroundColor: '#fff',
    color: theme.palette.text.primary,
    boxShadow: 'none',
    transition: 'background-color 0.2s ease, border-color 0.2s ease, color 0.2s ease',
    '&:hover': {
      borderWidth: 2,
      borderStyle: 'solid',
      borderColor: '#3f51b5',
      backgroundColor: theme.palette.grey[200],
      color: '#1a237e',
      boxShadow: 'none',
    },
    '&.MuiButton-outlined': {
      border: '2px solid',
      borderColor: theme.palette.grey[400],
      padding: theme.spacing(0.5, 2.25),
      '&:hover': {
        border: '2px solid',
        borderColor: '#3f51b5',
        backgroundColor: theme.palette.grey[200],
      },
    },
  },
  titleTypography: {
    fontWeight: 600,
    fontSize: '1.125rem',
    marginBottom: theme.spacing(1),
    color: '#222',
    width: '100%',
    textAlign: 'center',
  },
}));